#!/usr/bin/env python
# -*- coding: utf-8 -*-

from main import *
import pickle

L = [{"lst":"Ababou", "solde":1.7, "cns":0, "px":0},
    {"lst":"Algéri", "solde":-3.1, "cns":0, "px":0},
    {"lst":"Aniort", "solde":5.8, "cns":0, "px":0},
    {"lst":"Bonami", "solde":-13.4, "cns":0, "px":0},
    {"lst":"Borrien", "solde":69.4, "cns":0, "px":0},
    {"lst":"Bouchareissas", "solde":67.8, "cns":0, "px":0},
    {"lst":"Boulant", "solde":-0.6, "cns":0, "px":0},
    {"lst":"Burdin", "solde":4.8, "cns":0, "px":0},
    {"lst":"Chamorel", "solde":25.6, "cns":0, "px":0},
    {"lst":"Cobo", "solde":-0.6, "cns":0, "px":0},
    {"lst":"Collin", "solde":15.6, "cns":0, "px":0},
    {"lst":"Delattre", "solde":35.6, "cns":0, "px":0},
    {"lst":"Desvignes", "solde":37.2, "cns":0, "px":0},
    {"lst":"Dufourneau", "solde":49.2, "cns":0, "px":0},
    {"lst":"Duguet", "solde":325.2, "cns":0, "px":0},
    {"lst":"Duval", "solde":13.1, "cns":0, "px":0},
    {"lst":"Encinas", "solde":0.0, "cns":0, "px":0},
    {"lst":"Favre", "solde":29.6, "cns":0, "px":0},
    {"lst":"Fricard", "solde":-17.6, "cns":0, "px":0},
    {"lst":"Gannier", "solde":0.8, "cns":0, "px":0},
    {"lst":"Gardan", "solde":90.8, "cns":0, "px":0},
    {"lst":"Gein", "solde":-48.5, "cns":0, "px":0},
    {"lst":"Gilot", "solde":14.0, "cns":0, "px":0},
    {"lst":"Girardet", "solde":39.2, "cns":0, "px":0},
    {"lst":"Gomes", "solde":26, "cns":0, "px":0},
    {"lst":"Grand", "solde":44.6, "cns":0, "px":0},
    {"lst":"Gregoire", "solde":14.8, "cns":0, "px":0},
    {"lst":"Grezes-Besset", "solde":4.5, "cns":0, "px":0},
    {"lst":"Hebraud", "solde":47.8, "cns":0, "px":0},
    {"lst":"Herbreteau", "solde":34.4, "cns":0, "px":0},
    {"lst":"Honecker", "solde":75.6, "cns":0, "px":0},
    {"lst":"Jacquiet", "solde":54.1, "cns":0, "px":0},
    {"lst":"Kuhlmann", "solde":-28.4, "cns":0, "px":0},
    {"lst":"Lafaille", "solde":54.9, "cns":0, "px":0},
    {"lst":"Laurent", "solde":9.4, "cns":0, "px":0},
    {"lst":"Leple", "solde":6.0, "cns":0, "px":0},
    {"lst":"Mantion", "solde":47.5, "cns":0, "px":0},
    {"lst":"Marcelle", "solde":5.6, "cns":0, "px":0},
    {"lst":"Marie", "solde":21.4, "cns":0, "px":0},
    {"lst":"Mayakas", "solde":3.6, "cns":0, "px":0},
    {"lst":"Meillassoux", "solde":-8.1, "cns":0, "px":0},
    {"lst":"Missey", "solde":7.8, "cns":0, "px":0},
    {"lst":"Ortet", "solde":-11.4, "cns":0, "px":0},
    {"lst":"Paillard", "solde":186.6, "cns":0, "px":0},
    {"lst":"Pallares", "solde":-14.1, "cns":0, "px":0},
    {"lst":"Pelopidas", "solde":56.7, "cns":0, "px":0},
    {"lst":"Pierre", "solde":27.3, "cns":0, "px":0},
    {"lst":"Pineau", "solde":53.5, "cns":0, "px":0},
    {"lst":"Pinot", "solde":3.7, "cns":0, "px":0},
    {"lst":"Pourquier", "solde":57.8, "cns":0, "px":0},
    {"lst":"Schaffauser", "solde":489.2, "cns":0, "px":0},
    {"lst":"Segard", "solde":83.6, "cns":0, "px":0},
    {"lst":"Sochet", "solde":-4.9, "cns":0, "px":0},
    {"lst":"Soutille", "solde":18.6, "cns":0, "px":0},
    {"lst":"Tatigne", "solde":48.8, "cns":0, "px":0},
    {"lst":"Thouaille", "solde":39.0, "cns":0, "px":0},
    {"lst":"Vasseur", "solde":-1.0, "cns":0, "px":0},
    {"lst":"Vanzande", "solde":88.1, "cns":0, "px":0},
    {"lst":"Venard", "solde":7.6, "cns":0, "px":0},
    {"lst":"Weber", "solde":69.6, "cns":0, "px":0},
    {"lst":"Bellais", "solde":1.2, "cns":0, "px":0},
    {"lst":"De Chavigny", "solde":7.4, "cns":0, "px":0},
    {"lst":"Lebrun", "solde":24.8, "cns":0, "px":0},
    {"lst":"Gontier", "solde":41.0, "cns":0, "px":0},
    {"lst":"Perrot", "solde":35.6, "cns":0, "px":0},
    {"lst":"Dhalleine", "solde":1.8, "cns":0, "px":0},
    {"lst":"Teremate", "solde":21.0, "cns":0, "px":0},
    {"lst":"Auclerc", "solde":28.0, "cns":0, "px":0},
    {"lst":"Barbe", "solde":-7.9, "cns":0, "px":0},
    {"lst":"Begoc", "solde":8.2, "cns":0, "px":0},
    {"lst":"Bernard", "solde":0, "cns":0, "px":0},
    {"lst":"Coterot", "solde":9.0, "cns":0, "px":0},
    {"lst":"De Boisseson", "solde":17.0, "cns":0, "px":0},
    {"lst":"Evrard", "solde":14.4, "cns":0, "px":0},
    {"lst":"Garrault", "solde":10.2, "cns":0, "px":0},
    {"lst":"Glet", "solde":4.6, "cns":0, "px":0},
    {"lst":"Gregoire (2)","solde":13.0, "cns":0, "px":0},
    {"lst":"Gwinner","solde":15.8,"cns":0, "px":0},
    {"lst":"Herrier","solde":13.6,"cns":0, "px":0},
    {"lst":"Millet","solde":-9.0,"cns":0, "px":0},
    {"lst":"Philippe","solde":12.5,"cns":0, "px":0},
    {"lst":"Quervel","solde":6.0,"cns":0, "px":0},
    {"lst":"Stoeffel","solde":-0.8,"cns":0, "px":0},
    {"lst":"Tessaro","solde":13.0,"cns":0, "px":0},
    {"lst":"Wijas","solde":-8.8,"cns":0, "px":0},
    {"lst":"Cordonnier","solde":-17.5,"cns":0, "px":0},
    {"lst":"Ren","solde":-18.7,"cns":0, "px":0},
    {"lst":"Dauphin","solde":20.0,"cns":0, "px":0},
    {"lst":"Corinne","solde":-3.0,"cns":0, "px":0},
    {"lst":"Benisty","solde":-9.6,"cns":0,"px":0},
    {"lst":"Fabre", "solde":-20, "cns":0, "px":0}]
esc = {"pers":L, "n":len(L)}
pickle.dump(esc,open("escadronfile.txt","wb"))
